### ISSUE TITLE
Enable build without --report-unsupported-elements-at-runtime

### ISSUE THREAD

**Issue by morki** [micronaut-graal-tests/micronaut-jooq-graal#1]
Continuation of discussion in https://github.com/micronaut-graal-tests/micronaut-data-jdbc-graal/pull/1#issuecomment-646219436

The problem here is only SimpleFlatMapper, native image build failing with:

```
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.ClassLoader.defineClass1(ClassLoader, String, byte[], int, int, ProtectionDomain, String) is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method java.lang.ClassLoader.defineClass1(ClassLoader, String, byte[], int, int, ProtectionDomain, String) is reachable

Detailed message:
Trace: 
	at parsing java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
Call path from entry point to java.lang.ClassLoader.defineClass(String, byte[], int, int, ProtectionDomain): 
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1015)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:878)
	at org.simpleflatmapper.util.FactoryClassLoader.registerClass(FactoryClassLoader.java:43)
	at org.simpleflatmapper.reflect.asm.AsmFactory.registerClass(AsmFactory.java:58)
	at org.simpleflatmapper.reflect.asm.AsmFactory.createBiInstantiator(AsmFactory.java:218)
	at org.simpleflatmapper.reflect.InstantiatorFactory.getBiInstantiator(InstantiatorFactory.java:78)
	at org.simpleflatmapper.reflect.InstantiatorFactory.getBiInstantiator(InstantiatorFactory.java:53)
	at org.simpleflatmapper.map.mapper.MapperBiInstantiatorFactory.getBiInstantiator(MapperBiInstantiatorFactory.java:57)
	at com.oracle.svm.reflect.MapperBiInstantiatorFactory_getBiInstantiator_23ec79bb9f6764526f02e92475eb81ac02cc00e5_2647.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at javax.xml.transform.TransformerException.printStackTrace(TransformerException.java:345)
	at javax.xml.transform.TransformerException.printStackTrace(TransformerException.java:285)
	at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:761)
	at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception

Error: Image build request failed with exit status 1
```

With addition of this flag, error is gone and it is working in runtime, but we would like to try to make build working without this flag.

@ilopmar can you please help me with this? I know SimpleFlatMapper is not contained in JOOQ, but it is very common companion library, which enables 1:1, 1:N and other useful staff like discriminator mapping, which JOOQ does not provide out of the box.

**Comment by ilopmar** [comment]
Sorry but I didn't remember yesterday that `--report-unsupported-elements-at-runtime` is necessary at this moment for generating a native-image with H2, my bad.
Maybe there is no issue with SimpleFlatMapper with GraalVM. To be completely sure (or to configure it properly) we need to test with other databases that don't require it: Postgres, MariaDB,...

**Comment by morki** [comment]
@ilopmar I use it with postgres and the posted error message was from my build. It is related only to SimpleFlatMapper.

I think we have two solutions here:

1) remove SimpleFlatMapper from this test, because it tests JOOQ and JOOQ alone works great
2) try to fix the SimpleFlatMapper integration

I am for (2), because we use SimpleFlatMapper heavily in our projects, but it is up to you, because I have no "mental capacity" to resolve this, but I have time and can help you in every aspect if you would like to :)

**Comment by ilopmar** [comment]
Ohh, I didn't realize that the error was in SimpleFlatMapper. From the stacktrace it seems that the library does some bytecode manipulation with ASM so that's probably why it doesn't work with GraalVM.

What I do to debug the errors and to generate the right configuration files is using the GraalVM Tracing Agent. You can enable it adding the following to your `build.gradle`:
```groovy
run {
    jvmArgs = [
            "-agentlib:native-image-agent=experimental-class-loader-support,config-output-dir=tmp",
            "-Dorg.graalvm.nativeimage.imagecode=agent"
    ]
}
```
You start the application normally with `./gradlew run` (make sure you are using GraalVM JDK) and hit the different endpoints that use your code. The agent with "instrument" and "trace" your code and "record" all the classes and methods used. Then you stop the app and take a look at the files in `tmp` directory. I copy them to the `native-image` directory adapting them a little bit. For example I remove the `io.micronaut` entries from `reflect-config.json` and also from `resources-config.json`. 

Regarding the removal of `--report-unsupported-elements-at-runtime` it the application works fine with the flag when generating the native image, then you shouldn't worry too much. The GraalVM team recommends not using it, but if it works for the use case I think we can live with that.

What we could do later once everything work is opening an issue on GraalVM with a sample application that works with `--report-unsupported-elements-at-runtime` and saying that it doesn't work without it.

**More info about the Tracing agent:**
- https://medium.com/graalvm/introducing-the-tracing-agent-simplifying-graalvm-native-image-configuration-c3b56c486271
- https://github.com/oracle/graal/blob/master/substratevm/CONFIGURE.md

**Comment by morki** [comment]
Thank you, I will try a report results :)

**Comment by morki** [comment]
@ilopmar you can test in PR https://github.com/micronaut-graal-tests/micronaut-jooq-graal/pull/6 where H2 is replaced with Postgres and flag `--report-unsupported-elements-at-runtime` is used only for SimpleFlatMapper. If you remove it, you get the error message similar to the one I posted in first comment.

I tried your workflow with enabling tracing agent, but I dont think it is related to reflection or other generated files.
I tried it with generated files and the result is the same. I seems that the problem is use of ASM, especially this part in `ReflectionService` which uses ASM by default.

```java
	public static ReflectionService newInstance() {
		return newInstance(true);
	}

	private static final AsmFactory _defaultAsmFactory = new AsmFactory(ReflectionService.class.getClassLoader());

	public static ReflectionService newInstance(boolean useAsmGeneration) {
		return new DefaultReflectionService(useAsmGeneration && canSeeSetterFromContextClassLoader() ? _defaultAsmFactory : null);
	}
```

In runtime it probably detects it is not possible and does not use ASM, but the build is failing.

I you would like to help me, I will be very happy.

**Comment by morki** [comment]
Adding `.useAsm(false)` to `JdbcMapperFactory` builders like this does not help neither.

```java
        this.mapper = JdbcMapperFactory.newInstance()
                .useAsm(false)
                .addKeys("id", "pet_id")
                .newMapper(Owner.class)
```

**Comment by ilopmar** [comment]
The good news is that it is failing while creating the native-image so we can debug it easily.

Add the option `--debug-attach=5005` to `build-native-image.sh` and put a break point in the classes where it fails. Then run the `./build-native-image.sh` script and when the native image compilation starts you will see `Listening for transport dt_socket at address: 5005`

Go to IntelliJ and create a "Remote" configuration with the default options and click on the "Debug" button. It will connect to the process and the creation of the native image will continue. Then it will stop on your breakpoints inside IntelliJ. This way you can also see why the `.userAsm(false)` is not working. Maybe there is an issue with the library.

With the "learnings" about the debug you may be able to write some GraalVM Substitutions to replace the SimpleFlatMapper.

If that doesn't work, another approach I've done is cloning the repository of the library, add a lot of `println`s everywhere to display the values of some variables and to "mark" the code execution. Then I publish locally a snapshot version of the library and use it in my app.

**Comment by morki** [comment]
@ilopmar I did it! :)

```java
import com.oracle.svm.core.annotate.Substitute;
import com.oracle.svm.core.annotate.TargetClass;
import org.simpleflatmapper.reflect.DefaultReflectionService;
import org.simpleflatmapper.reflect.asm.AsmFactory;

@TargetClass(DefaultReflectionService.class)
final class DefaultReflectionServiceSubstitutions {
    @Substitute
    public AsmFactory getAsmFactory(ClassLoader classLoader) {
        return null;
    }
}
```

I would like to contribute it to `micronaut-sql` project, but I have some questions about referencing SimpleFlatMapper classes.
- We probably does not include SimpleFlatMapper as dependency to `micronaut-jooq`, so how to reference the class in `@TargetClass` annotation?
- I was looking that it has `className` property, but will it produce warning for users that do not include SimpleFlatMapper in their classpath?
- What about `AsmFactory` as return type of `getAsmFactory`?
- Is it something where we should use `@AutomaticFeature`?

**Comment by ilopmar** [comment]
Woow, you're awesome! :tada: 

- I think you can include the SimpleFlatMapper dependency as `compileOnly` so it's not included as a transitive dependency in `micronaut-jooq`. Then you should try how does behave when SimpleFlatMapper is not on the classpath on the application, because with Gradle you never know :stuck_out_tongue_closed_eyes: 
- Using `compileOnly` allows you to use `value` instead of `className`. Keep in mind that you still need `org.simpleflatmapper.reflect.asm.AsmFactory` for the return type of the method. In any case I think (not 100% sure) that it won't be a problem because if there is no class matching the `@Target` then nothing should be done. You can put a few `println`s there and check the output with and without SimpleFlatMapper on the classpath.
- You can use `onlyWith` parameter to make the `@TargetClass` conditional. I haven't used it before but you have an example on the annotation itself.
- Regarding the `@AutomaticFeature` I think it won't work for this case because you want to execute a method substitution, not registering classes or something like that. If the `@TargetClass` doesn't work when SimpleFlatMapper is not on the classpath, then maybe you can create an `@AutomaticFeature` that is executed at the very beginning, look if the SimpleFlatMapper is on the classpath and set an static variable somewhere. Then use that static variable in `onlyWith` condition on the `@TargetClass` annotation. It seems a little bit ugly and convoluted but, as I said, I think it won't be necessary.

**Comment by morki** [comment]
Thank you very much @ilopmar, PR is ready in `micronaut-sql` project :)

**Comment by morki** [comment]
Closing as it is resolved in `micronaut-sql` and now we don't have to use this flag for databases other than H2.
