### ISSUE TITLE
Create branches with other databases

### ISSUE THREAD

**Issue by morki** [micronaut-graal-tests/micronaut-jooq-graal#2]
Continuation of discussion in https://github.com/micronaut-graal-tests/micronaut-data-jdbc-graal/pull/1#issuecomment-646219436

Like other `micronaut-sql` test repos, we should provide multiple branches with multiple databases.

Example from https://github.com/micronaut-graal-tests/micronaut-data-jdbc-graal:

> Micronaut Data JDBC Graal
> warning The master branch is not used anymore.
> Checkout branches for each specific database: h2, postgres, oracle, mariadb, sqlserver and mysql.

**Comment by morki** [comment]
I think we should do that only after resolving #1 or abandoning SimpleFlatMapper. I would be happy to create PRs for that.

**Comment by ilopmar** [comment]
I have mixed feelings about introducing more branches for other databases because that would increase the CI time a bit. On the other hand I would like to at least try with other database to make sure it works with a "real" database and to make sure that `--report-unsupported-elements-at-runtime` is not needed (as discussed in #1).

If you can send a PR for Postgres (for example), it would be great.

Btw, I modified your code a little bit here https://github.com/micronaut-graal-tests/micronaut-jooq-graal/commit/120abd03b8a980c7780d1035ac6d10e2d7800363 to return the same output as in JDBC/JPA test apps. As I said before I don't have experience with jOOQ so maybe that's not the best approach. Specially, I'm not really happy about the `PetType` enum part. Feel free to submit first a PR to `master` branch to cleanup/improve what you think and then we can branch off there to work on other databases.

**Comment by ilopmar** [comment]
For now I think we'll stick to H2 and Postgres. I don't think adding MariaDB or MySQL adds any additional value because we already have other test applications for those databases.
